### PR TITLE
fix(Quiz Attempt Submitted): Replace raw score with raw grade.

### PR DESCRIPTION
**Pull request by BrendanHalley**
**Description**
The raw score now returned in the xAPI statement is the grade for the attempt. This fixes the issue where scaling was wrong because the matching fields are being used for max and min.

In the past successfully completed questions were returned as the raw value. This change removes no data as it's already in the answered statements for each question.

**Related Issues**
- #271 

**PR Type**
- Fix

### CODE REVIEW

**Comment by garemoko** [comment]
Are you able to explain the difference between the two fields i.e. the one currently being used for the score vs. the one that you are changing to?

**Comment by BrendanHalley** [comment]
Old: Score based on a total of correctly answered questions. Moodle defaults to 1 per question.

New: Grade from quiz attempt - Moodle handles all logic based around grading and scaling the grade. This is used for marking so seems most appropriate to be used in this context in the statement.

**Comment by garemoko** [comment]
That makes sense to me.

**Review by ryasmi — APPROVED** [review]
Thanks @BrendanHalley, looks good and thanks for updating the tests. Since I don't know Moodle very well, I'm going to have to trust you and the community on this one.

**Comment by ryasmi** [comment]
Hmmm this seems to be failing tests now @BrendanHalley. @garemoko do you think this might have been affected by your changes since I just merged those?

**Comment by BrendanHalley** [comment]
@ryansmith94 The change's merged in include a new test that's missing some data that this pull request requires. I'll fix it up now :)

**Comment by BrendanHalley** [comment]
@ryansmith94 All sorted

**Comment by ryasmi** [comment]
Wow that was fast work, thanks @BrendanHalley 👍

**Pull request merged**
