### PR TITLE
Add feedback integration test

### PR DESCRIPTION
**Pull request by garemoko**
See https://github.com/LearningLocker/Moodle-xAPI-Translator/pull/39#issuecomment-216547192

### CODE REVIEW

**Comment by ryasmi** [comment]
What's the status of this @garemoko?

**Comment by garemoko** [comment]
Worryingly, my memory of this PR is hazy.  Looking at the changes, I think it's done.

**Comment by ryasmi** [comment]
Awaiting merge of LearningLocker/Moodle-xAPI-Translator#39 and updated dependencies here then @jlowe64.

**Comment by jlowe64** [comment]
I'll focus 100% on this repo next week to get all the clean up stuff done and PRs merged and do a release. Sorry about the delays on my part.

**Comment by ryasmi** [comment]
Awesome. No worries @jlowe64.

**Comment by jlowe64** [comment]
Fixed an issue with the TestRepository:

https://github.com/LearningLocker/Moodle-Log-Expander/commit/7c2eb631c2cf7530411b5967c82e55dce05009b7

This is good to integrate. Passes all local integration tests.

**Pull request merged**
