### PR TITLE
Allow get_string_html_removed transformer to handle null input

### PR DESCRIPTION
**Pull request by srio0180**
**Description**
- Allow get_string_html_removed transformer to handle null input

**Related Issues**
- #838

**PR Type**
- Fix

### CODE REVIEW

**Comment by davidpesce** [comment]
Thank you for contributing this! Alone, I think this would cause errors further down the line. If you could add the following within the function, I think that would cover it:
```
    if ($string === null) {
        return '';
    }
```

**Comment by ryasmi** [comment]
Hi @davidpesce - you happy to get this merged? We know someone that we think has run into an issue with this one too.
```
Scheduled task failed: Emit records to LRS (logstore_xapi\task\emit_task),Argument 1 passed to src\transformer\utils\get_string_html_removed() must be of the type string, null given, called in /var/www/html/moodle/admin/tool/log/store/xapi/src/transformer/events/mod_quiz/question_answered/truefalse.php on line 68
```

**Comment by davidpesce** [comment]
Sorry for the delay on this one, @srio0180. Thanks for contributing!
@ryansmith94 - yeah, this one is good to go and merged now.

**Comment by srio0180** [comment]
Thanks

**Comment by ryasmi** [comment]
You're amazing, thanks @davidpesce! ❤️

**Comment by ryasmi** [comment]
@davidpesce would it be possible to create a release tag for that? Seems it wasn't merged with the [Semantic Release commit format](https://github.com/semantic-release/semantic-release#commit-message-format) to trigger the automated release process (assuming Semantic Release is in use here).

**Comment by davidpesce** [comment]
@ryansmith94 I'm reviewing a massive PR and hoping to get it in with that. Stay tuned!

**Pull request merged**
