### PR TITLE
feat(JISC): Adds jisc extensions behind `send_jisc_data` setting.

### LINKED ISSUE #422: Add JISC context extensions to statements.
JISC are using these context extensions to all statements, I'm not sure whether to add them behind a flag or whether they're useful anyway. This is part of an effort to get all users of JISC's fork back to using the core plugin (#50 and #66 will also be needed).

```json
{
  "http://xapi.jisc.ac.uk/sessionId": "sesskey()",
  "http://id.tincanapi.com/extension/ip-address": "$event->ip",
  "http://xapi.jisc.ac.uk/courseArea": {
    "http://xapi.jisc.ac.uk/vle_mod_id": "$course->shortname"
  },
  "http://xapi.jisc.ac.uk/statementCat": "VLE"
}
```

### PR DESCRIPTION
**Pull request by ryasmi**
**Description**
Adds jisc extensions behind `send_jisc_data` setting.

```json
{
  "http://xapi.jisc.ac.uk/sessionId": "sesskey()",
  "http://id.tincanapi.com/extension/ip-address": "$event->ip",
  "http://xapi.jisc.ac.uk/courseArea": {
    "http://xapi.jisc.ac.uk/vle_mod_id": "$course->shortname"
  },
  "http://xapi.jisc.ac.uk/statementCat": "VLE"
}
```

**Related Issues**
- Resolves #422 

**PR Type**
- Enhancement

### CODE REVIEW

**Comment by ryasmi** [comment]
@garemoko / @davidpesce you guys happy with this?

**Comment by davidpesce** [comment]
I think this looks good. The only concern that I'm remembering is with the session key. It looks like you made it unique by including the base URL for JISC's platform as the first part, then appended the sessionId.

I'm not sure where we landed on whether the sessionIds could be re-used (or collisions occurring). But with it being in an extension I don't see any technical concerns.

**Review by davidpesce — APPROVED** [review]

**Comment by ryasmi** [comment]
I think the collisions are ok, I think it can be combined with other values to make it more unique.

**Comment by ryasmi** [comment]
Thanks for taking a look @davidpesce 👍

**Pull request merged**
