### PR TITLE
Scorm events

### PR DESCRIPTION
**Pull request by jlowe64**
Expanding events to handle scorm submissions.

### CODE REVIEW

**Comment by jlowe64** [comment]
In progress!

**Comment by davidpesce** [comment]
Quick question on the status of this PR. Is it ready to be merged?

**Comment by jlowe64** [comment]
@davidpesce unfortunately I do not have the time to work on the feedback given in the library repos (which are necessary to being able to merge this). Since I am leaving my current organisation, I don't foresee having the time to work on Moodle work on the side in the future. I will attempt to reach out to some orgs that showed some interest in the plugin and instill some renewed vigor into my current organisation to hopefully get someone (or a group of people) to work on this in the near future. Of course, you would be welcome to take over where I left off and finish things up if you like?

Perhaps @ryansmith94 (HT2) or @garemoko (Watershed) could help gather up these resources?

**Comment by ryasmi** [comment]
I don't have any time currently, sorry.

**Comment by davidpesce** [comment]
Can we schedule a call to discuss transitioning this? I'm curious on getting the full status of PRs and Issues. I have two interested clients who may fund this development but need a clear idea of what will be involved.

**Comment by ryasmi** [comment]
Hey @davidpesce, I'll have a chat with James tomorrow. I'm sure we can sort out a call.

**Comment by davidpesce** [comment]
@garemoko here's one

**Comment by garemoko** [comment]
@davidpesce what do you want from me here?

**Comment by davidpesce** [comment]
The four PRs I tagged you in are all related. You weighed in (a while ago) on a few of the others. I was curious on your input as to whether the current direction is still what you would recommend.

**Comment by garemoko** [comment]
I never found time to test these properly. 

The general direction i think we should take with SCORM is to follow the ADL SCORM profile.

**Review by ryasmi — APPROVED** [review]

**Pull request merged**
