### PR TITLE
#130 - Delete records from 'mdl_logstore_xapi_log' after successfully sent them to LRS

### PR DESCRIPTION
**Pull request by Dasuntha**
**Description**
- Delete records from 'mdl_logstore_xapi_log' after successfully sent them to LRS

**Related Issues**
- #130 

**PR Type**
- Fix or Enhancement

### CODE REVIEW

**Comment by davidpesce** [comment]
Hi, Dasuntha. Thanks for contributing this! I should be able to test this week.

**Comment by bseclier** [comment]
I just test it, it works very well. Thanks @Dasuntha !

**Review by ryasmi — APPROVED** [review]

**Comment by ryasmi** [comment]
Thanks @bseclier, just waiting for Travis to finish it's build with the recent updates to the master branch in here 👍

**Comment by ryasmi** [comment]
@HT2Bot is now creating a new release with this PR via Travis.

**Comment by andreasilvestriunitn** [comment]
Hi, we have this problem in 2.2.4 version with Moodle 3.5+ (Build: 20180628) . I think the PR #158 introduced a regression.
I think that in the file store.php the row 158
$k = $xapievents[$key]['context']['extensions'][Event::CONTEXT_EXT_KEY]['id'];
should be
$k = $statements[$key]['context']['extensions'][Event::CONTEXT_EXT_KEY]['id'];
Thanks.

**Pull request merged**
