### PR TITLE
Minor php linting fix

### PR DESCRIPTION
**Pull request by syn**
**Description**
- Simple php linting fix.
The code in master was had a ;  ending an array definition that was tripping up the php linting checks in our ci.

**PR Type**
- Fix

### CODE REVIEW

**Comment by mattporritt** [comment]
Is anyone going to accept or comment on this PR? 
You have code on master that has a syntax error in it.

**Comment by ryasmi** [comment]
Hi @mattporritt, the plugin is going through a major refactor right now, so the majority of the code will become obsolete in the next couple of weeks. Whilst the code on master is currently failing an external linting check, the issue is a linting error in the test code hence not a priority. No comment will have been made on this PR initially since it's failing our CI checks.

**Comment by syn** [comment]
There you go, I have also fixed the CI checks, which were also failing on Master, arguably that's more important that the one character linting fix.

**Comment by ryasmi** [comment]
Thanks @syn 👍

**Pull request merged**
