### PR TITLE
It's no longer necessary to instantiate \MXTranslator\Events\Event and invoke its 'read' method just to get at the 'context' ext key

### PR DESCRIPTION
**Pull request by mikemcgowan**
Please see [this PR](https://github.com/LearningLocker/Moodle-xAPI-Translator/pull/66).

### CODE REVIEW

**Comment by mikemcgowan** [comment]
I have now rebased this work against v2.0.0 (specifically, against commit 36da01e).

I have brought in the changes made in [the other repo's PR](https://github.com/LearningLocker/Moodle-xAPI-Translator/pull/66) into this PR.

**Comment by mikemcgowan** [comment]
@davidpesce any word on getting this merged?

**Review by ryasmi — APPROVED** [review]
Not 100% but this seems correct @davidpesce

**Comment by mikemcgowan** [comment]
I've now rebased this PR following the merge of #119

**Review by ryasmi — APPROVED** [review]

**Comment by ryasmi** [comment]
Hey @mikemcgowan, sorry it's taken so long to take action here, if you can merge the master branch back into yours I can get this merged :smile:

**Comment by davidpesce** [comment]
@mikemcgowan Any chance you were able to merge the master branch into these changes? If you aren't able to do it, let me know and I'll submit a separate PR.

**Comment by davidpesce** [comment]
Going to re-submit this.

**Pull request closed without merging**
