### PR TITLE
feat: Adds support for multichoiceset quiz questions.

### PR DESCRIPTION
**Pull request by caperneoignis**
added an additional case statement to handle multichoiceset qtype. Will need to add a better default handler for future qtypes.

**Description**
- adds an additional handling of one more question type.

**Related Issues**
- didn't make a related issue.

**PR Type**
- Fix

### CODE REVIEW

**Comment by caperneoignis** [comment]
@ryansmith94 I added an updated qtype handling. I will work on the default handling of future question types later. This is just a quick addition for a qtype I am using and is missing. It should be handled as the multichoice. Since if it is correct or not is handled by Moodle and will display properly if different.

**Comment by ryansmith94** [comment]
I think we should probably create a test for this in `tests/mod_quiz/attempt_submitted` in case someone changes the way this works in future and forgets to add tests. For now it can just be a duplicate of the `tests/mod_quiz/attempt_submitted/multichoice` folder but replace uses of "multichoice" with "multichoiceset".

**Review by ryasmi — CHANGES_REQUESTED** [review]
I think we should probably create a test for this in `tests/mod_quiz/attempt_submitted` in case someone changes the way this works in future and forgets to add tests. For now it can just be a duplicate of the `tests/mod_quiz/attempt_submitted/multichoice` folder but replace uses of "multichoice" with "multichoiceset".

**Comment by caperneoignis** [comment]
Okay I'll update. Do you want me to include the additional changes I have done to the multichoice statement? Since I am adding the correct response and potential answers to it or put that in other branch?

**Comment by caperneoignis** [comment]
nm I will use seperate branch

**Comment by ryasmi** [comment]
Okay can this be closed in favour of #233?

**Comment by caperneoignis** [comment]
@ryansmith94 This branch is just merging the question type, not the answers or the other items, you said you may not want. So this is so the question type all or nothing can be used in the handler. While the other branch is adding the other items that may or maynot be merged.

**Comment by ryasmi** [comment]
Got it, thanks for clarifying 👍

**Review by ryasmi — APPROVED** [review]

**Comment by ryasmi** [comment]
Thanks for adding the tests @caperneoignis, just waiting to make sure the build passes before I merge this because I had to merge master into this PR 👍

**Pull request merged**
