### PR TITLE
Update store.php

### PR DESCRIPTION
**Pull request by deedey**
Added moodle config proxy parameters

### CODE REVIEW

**Comment by ryasmi** [comment]
Ready to merge for the next minor release @jlowe64 👍

**Comment by ryasmi** [comment]
Actually @jlowe64, before merging this, ensure that the tincan php library has been updated in the composer.json file and composer.lock file.

**Comment by davidpesce** [comment]
@ryansmith94 do you remember which version of TinCanPHP you were referencing above?

**Comment by ryasmi** [comment]
No I don't sorry @davidpesce. What's the reasoning for using submodules? My only qualm would be the bad press I've read about using submodules in the *past*.

**Comment by garemoko** [comment]
I would much rather we use submodules than composer. I'm a big submodules fan.

**Comment by davidpesce** [comment]
I think it did get some bad press for being used wrong. I'm fine either way but do prefer submodules. I don't want to rock the boat so I'll leave it as is!

**Comment by davidpesce** [comment]
TinCan PHP 1.0 is a required dependency in this PR: https://github.com/xAPI-vle/moodle-logstore_xapi/pull/95

Once that has been merged, this should be OK to merge as well.

**Comment by davidpesce** [comment]
@ryansmith94 should I create another issue/PR with the camelcase fixes? Or should I ignore it?

**Comment by ryasmi** [comment]
Nah ignore that for now, need to just have a sweep through the repository and make code climate happy.

**Pull request merged**
